version: '3'

services:

  # TODO: DB用とバックエンド用コンテナを追加する

  # フロントエンド用コンテナ
  app:
    build: ./frontend
    volumes:
      - ./src:/src:cached
      # - node_modules:/src/node_modules
      # ↑ 次回起動後にコメントアウトを解除
    # working_dir: "/frontend"
    ports:
      - "3000:3000"
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=3000
      - CHOKIDAR_USEPOLLING=true
volumes:
  nuxt_node_modules:
